// Copyright 2017-2021 @axia-js/ui-settings authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @axia-js/dev, do not edit

export const packageInfo = { name: '@axia-js/ui-settings', version: '1.1.0' };
